passed tests
mate-academy/react_todo-app-with-api pull request #1085
Opened 2024-02-07 12:21 UTC by ssaviak

[DEMO LINK](https://ssaviak.github.io/react_todo-app-with-api/)

2024-02-08 09:19 UTC, VasiliyYarosh approved these changes
Brilliant, good job!

2024-02-08 14:17 UTC, olya-shyian requested changes
Thank you for the task!🌸

Try to remove this pop up when click on radio button
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/91946036/77574f63-f577-47b6-8215-c643c0354109)

2024-02-08 14:17 UTC, olya-shyian commented on src/components/TodoItem.tsx
> +  };
it looks like you have the same code 3 times
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/91946036/e4460e07-0c5e-4945-a296-5e7ee4b1471c)
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/91946036/c5762e46-d34a-40ea-9420-246c398f65f3)

could you do some code refactoring?

you can keep this in TodoContext and reuse everywhere you need

2024-02-08 14:17 UTC, olya-shyian commented on src/components/TodoItem.tsx
> +      .finally(() => idsToUpdate(null));
the same with update
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/91946036/58051499-524e-4756-b715-afa8742343df)
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/91946036/30d22dcb-b165-4a2e-bf08-f834eb0f1839)

2024-02-08 14:17 UTC, olya-shyian commented on src/contexts/TodoContext.tsx
> +      }
move this function to `utils` folder please

2024-02-08 14:17 UTC, olya-shyian commented on src/types/ErrorMessage.ts
> +  FailedUpdateRequest = 'Unable to update a todo',
you can delete one
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/91946036/0ddc9de8-b6ea-4738-9e47-cfe81ff973ad)

2024-02-09 17:22 UTC, DanilWeda reviewed
Great! 
Approved.
Thanks.

2024-02-09 17:22 UTC, DanilWeda commented on src/contexts/TodoContext.tsx
> +    filteredTodos: todos.filter(todo => {
need to move this function to another file

2024-02-09 17:22 UTC, DanilWeda approved these changes
Approved*

2024-05-13 11:23 UTC, closed without merging