Task without changing and deploy
mate-academy/react_todo-app-with-api pull request #1097
Opened 2024-02-08 21:06 UTC by YevhenOstrovskiy

2024-02-10 19:38 UTC, YevhenOstrovskiy commented
[DEMO LINK](https://YevhenOstrovskiy.github.io/react_todo-app-with-api/)

2024-02-11 14:44 UTC, l0ad1nggg requested changes
Looks great, but tests should pass(

2024-02-15 09:42 UTC, DanilWeda approved these changes
Good job. 
Approved! 
Thanks!

2024-02-15 09:42 UTC, DanilWeda commented on src/components/TodoItem/TodoItem.tsx
> +type Props = {
use interface prefer. 
Types have unique features but the interface is best for scaling.

2024-02-15 09:42 UTC, DanilWeda commented on src/components/TodoItem/TodoItem.tsx
> +                console.log('escape was pushed');
remove console.
write handler for it

2024-02-15 09:42 UTC, DanilWeda commented on src/components/TodoList/TodoList.tsx
> +type Props = {
use interface prefer. 
Types have unique features but the interface is best for scaling.

2024-09-18 07:09 UTC, closed without merging