todo app with api
mate-academy/react_todo-app-with-api pull request #1240
Opened 2024-05-10 12:53 UTC by andreyysak

[DEMO LINK](https://andreyysak.github.io/react_todo-app-with-api/)

2024-05-10 13:25 UTC, IvanFesenko requested changes
Good job, check my comments:
- Loader is on all todos insted of one that get update
![2024-05-10_16h15_48](https://github.com/mate-academy/react_todo-app-with-api/assets/61904995/02785116-8b31-4a92-8278-3fb2af0f5285)
https://github.com/mate-academy/react_todo-app-with-api/assets/61904995/c47ccba9-d94f-4db2-bf4a-4489dbda7ad9
- Check this case
https://github.com/mate-academy/react_todo-app-with-api/assets/61904995/8b95f655-c337-4b92-baa3-4c858caa66f1

2024-05-10 13:25 UTC, IvanFesenko commented on src/components/Header.tsx
> +          onClick={() => toggleAll()}
```suggestion
          onClick={toggleAll}
```

2024-05-11 08:55 UTC, etojeDenys requested changes
1. you should show the loader on todos that you changed on the toggle click

https://github.com/mate-academy/react_todo-app-with-api/assets/70220667/0e038ead-3ff7-45f1-b43b-b9d22514fede

2. the same with the "Clear completed" button
3. looks broken, STR(steps to reproduce): 
- press spaces a few times on the input
- press enter after that

https://github.com/mate-academy/react_todo-app-with-api/assets/70220667/f6187dd2-c7a2-462e-9886-ff89257e91f4

2024-05-18 16:57 UTC, vadiimvooo requested changes
Almost done. There are two problems which should be fixed.
1. There is bug when you click toggle all button your completed todos have loader as well.
https://www.loom.com/share/5c9ab6545c1d429592a8344341406236
2. Something wrong with your input on todo editing
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/108701488/66424c70-00d9-4aef-be6f-95186434a8f7)

2025-04-12 10:07 UTC, closed without merging