add todo_app-with-api
mate-academy/react_todo-app-with-api pull request #1295
Opened 2024-05-29 14:32 UTC by vneholiuk

[DEMO LINK](https://vneholiuk.github.io/react_todo-app-with-api/)

2024-05-29 18:18 UTC, TarasHoliuk requested changes
Great job! Works perfect
Added a few small comments to refactor your code a bit

2024-05-29 18:18 UTC, TarasHoliuk commented on src/App.tsx
> +  let filterTodos = todos;
```suggestion
  let filteredTodos = todos;
```
filterTodos, with verb in name sounds like a function name

2024-05-29 18:18 UTC, TarasHoliuk commented on src/App.tsx
> +                  isLoading={loadingTodos.includes(0)}
we always want show loader for tempTodo
```suggestion
                  isLoading
```
So you can also avoid adding `0` to loadingTodos (BTW, there are only ids, not todos, so better name is `loadingTodoIds`)

2024-05-29 18:18 UTC, TarasHoliuk commented on src/components/TodoItem.tsx
> +  const [isRemaining, setIsRemaining] = useState(false);
```suggestion
  const [isRenaming, setIsRenaming] = useState(false);
```
I guess you mean this

2024-05-29 18:18 UTC, TarasHoliuk commented on src/components/TodoItem.tsx
> +  onDelete = () => {},
you can do it optional and check before calling it

but also, you can improve the current approach: create some `noOperation` function (you can create better name)) above component and use it as default value for each one

2024-05-29 18:18 UTC, TarasHoliuk commented on src/App.tsx
> +    <div className="todoapp">
this component became quite big now
let's split it into a few separate components

2024-05-30 09:15 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-05-30 09:15 UTC, volodymyr-soltys97 commented on src/App.tsx
> +      .then((response: React.SetStateAction<Todo[]>) => setTodos(response))
```suggestion
      .then(setTodos)
```

2024-05-30 09:15 UTC, volodymyr-soltys97 commented on src/App.tsx
> +                    selected: status === 'all',
Create a enum for 'all', 'active', 'completed' and use it everywhere

2024-05-31 06:19 UTC, volodymyr-soltys97 approved these changes
Well done! 🔥

2024-11-16 15:58 UTC, closed without merging