Complete Task
mate-academy/react_todo-app-with-api pull request #1546
Opened 2024-12-19 15:40 UTC by RomanMartseniuk

[DEMO LINK](https://romanmartseniuk.github.io/react_todo-app-with-api/)

2024-12-20 08:34 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2024-12-20 08:34 UTC, volodymyr-soltys97 commented on src/components/Footer/Footer.tsx
> +        }}
```suggestion
        onClick={deleteCompletedTodos}
```

2024-12-20 08:34 UTC, volodymyr-soltys97 commented on src/components/Header/Header.tsx
> +          }}
```suggestion
          onClick={completeFunc}
```

2024-12-20 08:34 UTC, volodymyr-soltys97 commented on src/components/Header/Header.tsx
> +            active: todos.filter(todo => !todo.completed).length === 0,
Move this logic from jsx to the helper variable and use it here

2024-12-20 08:34 UTC, volodymyr-soltys97 commented on src/components/Header/Header.tsx
> +              createFunc();
Use a more descriptive name for all functions, for example you here you can use `handleCreateTodo`
```suggestion
              handleCreateTodo();
```

2024-12-20 08:34 UTC, volodymyr-soltys97 commented on src/components/TodoItem/TodoItem.tsx
> +          onChange={() => setTodoCompleted()}
Fix it everywhere 
```suggestion
          onChange={setTodoCompleted}
```

2024-12-21 11:21 UTC, etojeDenys requested changes
looks like you forgot to apply styles for edit inputs
<img width="658" alt="image" src="https://github.com/user-attachments/assets/14f81caf-c027-4510-b1f5-0f26d871e899" />

2024-12-21 11:21 UTC, etojeDenys commented on src/components/TodoList/TodoList.tsx
> +          loading={true}
```suggestion
          loading
```

2024-12-22 15:10 UTC, VitaliyBondarenko1982 approved these changes
Good job.

2025-12-26 21:31 UTC, closed without merging