solution was added
mate-academy/react_todo-app-with-api pull request #157
Opened 2022-11-10 20:16 UTC by Maksym845

- [DEMO LINK](https://Maksym845.github.io/react_todo-app-with-api/)

2022-11-14 09:20 UTC, Veremchukk approved these changes
GJ. But try to fix this problem

2022-11-14 09:22 UTC, Maksym845 commented
> GJ. But try to fix this problem

Yes, I forgot about this problem, thank you)

2022-11-14 13:49 UTC, Anna-Tkachenko requested changes

2022-11-14 13:49 UTC, Anna-Tkachenko commented on src/App.tsx
> +    if (todos) {
this check is redundant, you always have the link to array in todos variable

2022-11-14 13:49 UTC, Anna-Tkachenko commented on src/App.tsx
> +      setVisibleTodos(todos.filter((todo: Todo) => {
use functional setState if you change it according to the current value

2022-11-14 13:49 UTC, Anna-Tkachenko commented on src/App.tsx
> +  };
todos variable always store an array

2022-11-14 13:49 UTC, Anna-Tkachenko commented on src/App.tsx
> +        const apiTodos = await getTodos(user.id).then(gotTodos => gotTodos);
then after await function is redundant here

2022-11-14 13:49 UTC, Anna-Tkachenko commented on src/App.tsx
> +    increaseCounter();
for what purpose did you add counter value? can we calculate it according to the total length of todos?

2022-11-14 13:49 UTC, Anna-Tkachenko commented on src/App.tsx
> +        }, todo.id);
let's not change todos that are already completed / uncompleted

2022-11-14 13:49 UTC, Anna-Tkachenko commented on src/App.tsx
> +        || updatingError) && (
let's create separate variable for storing the final result of this condition and use this variable in jsx

2022-11-16 14:13 UTC, Anna-Tkachenko approved these changes
Good job! 🔥

2022-11-16 14:13 UTC, Anna-Tkachenko commented on src/App.tsx
> +    todos?.forEach(async (todo) => {
todos variable can't be undefined or null, so ? sign is redundant here

2022-11-16 14:13 UTC, Anna-Tkachenko commented on src/App.tsx
> +              }}
will be better to create separate variable for storing this object

2023-04-28 17:14 UTC, closed without merging