almost done
mate-academy/react_todo-app-with-api pull request #221
Opened 2022-12-18 22:58 UTC by mitattt

[DEMO LINK](https://mitattt.github.io/react_todo-app-with-api/)

not completed yet

2022-12-20 07:48 UTC, MXMUK requested changes
Good work buddy, but let's implement 'toggleAll' button

2022-12-20 07:48 UTC, MXMUK commented on src/components/Header.tsx
> +      />
Add the ability to toggle the completed status of all the todos with the `toggleAll` checkbox. 4 point in checklist

2022-12-20 07:48 UTC, MXMUK commented on src/App.tsx
> +    } catch (_) {
```suggestion
    } catch {
```

2022-12-20 07:48 UTC, MXMUK commented on src/components/Todo.tsx
> +        setNewTitle(todo.title);
why you set new title?

2022-12-20 11:48 UTC, mitattt commented on src/components/Todo.tsx
> +        setNewTitle(todo.title);
because its the new title :D

2022-12-20 11:59 UTC, MXMUK approved these changes
Well done 🔥

2022-12-21 14:11 UTC, denys-danyliuk requested changes
remove this bar is there is no todos
<img width="598" alt="Знімок екрана 2022-12-21 о 15 42 59" src="https://user-images.githubusercontent.com/106310796/208925015-7fe3de56-5d40-46ee-a0c8-1e122ed7c9dc.png">

2022-12-21 14:11 UTC, denys-danyliuk commented on src/App.tsx
> +      setCurrError('Something went wrong :(. We can not load user`s todos');
add this type of error to Errors

2022-12-21 14:11 UTC, denys-danyliuk commented on src/App.tsx
> +  const completedTodos = todos.filter(todo => todo.completed);
useMemo

2022-12-21 14:11 UTC, denys-danyliuk commented on src/components/Footer.tsx
> +          hidden: completedTodos.length === 0,
```suggestion
          hidden: !completedTodos.length,
```

2022-12-21 14:11 UTC, denys-danyliuk commented on src/components/Header.tsx
> +      />
it doesn't work right
<img width="598" alt="Знімок екрана 2022-12-21 о 16 04 32" src="https://user-images.githubusercontent.com/106310796/208924973-80d48cea-22fe-4470-833f-7f124f58942d.png">
<img width="664" alt="Знімок екрана 2022-12-21 о 16 04 26" src="https://user-images.githubusercontent.com/106310796/208924980-6cd0c015-83f8-4479-9a2b-b6e16f329abf.png">

2022-12-23 09:34 UTC, denys-danyliuk approved these changes

2022-12-23 09:34 UTC, denys-danyliuk commented on src/App.tsx
>    }, []);
you can add user to array of deps so when user have changed there will be his todos

2022-12-23 09:34 UTC, denys-danyliuk commented on src/App.tsx
>    }, []);
also, do you really need this? you have identical function at 142 line

2022-12-23 09:34 UTC, denys-danyliuk commented on src/components/TodoList.tsx
> +  const visibleTodos = getVisibleTodos;
:harold:?

2025-01-16 21:01 UTC, closed without merging