Solution
mate-academy/react_todo-app-with-api pull request #236
Opened 2022-12-31 13:43 UTC by Ivanenko1402

[DEMO LINK](https://Ivanenko1402.github.io/react_todo-app-with-api/)

2023-01-02 11:39 UTC, Anastasiia-Svintsova requested changes
Prevent adding empty strings, please

https://user-images.githubusercontent.com/99403198/210225851-c4edd578-22ba-44a1-b95c-42b70c2fbaff.mov

2023-01-02 11:39 UTC, Anastasiia-Svintsova commented on src/components/ErrorNotification/ErrorNotification.tsx
> +      {text}
```suggestion
        aria-label="x"
      />
      {text}
```

2023-01-02 11:39 UTC, Anastasiia-Svintsova commented on src/components/Filter/Filter.tsx
> +            selected: filterBy === 'all',
Use the enum here for the `all` value

2023-01-02 11:39 UTC, Anastasiia-Svintsova commented on src/components/Filter/Filter.tsx
> +            selected: filterBy === 'active',
And here

2023-01-02 11:39 UTC, Anastasiia-Svintsova commented on src/components/Filter/Filter.tsx
> +            selected: filterBy === 'completed',
And here

2023-01-02 11:39 UTC, Anastasiia-Svintsova commented on src/components/NewTodo/NewTodo.tsx
> +          onClick={() => changeAllNotCompleted()}
```suggestion
          onClick={changeAllNotCompleted}
```

2023-01-02 11:39 UTC, Anastasiia-Svintsova commented on src/components/TodoItem/TodoItem.tsx
> +    if (item.title === inputValue || !inputValue) {
Let's destructure item
```
const { title, id, userId, completed } = item;

2023-01-02 11:39 UTC, Anastasiia-Svintsova commented on src/components/TodoItem/TodoItem.tsx
> +              // eslint-disable-next-line jsx-a11y/no-autofocus
Try not to disable eslint, get used to fixing the error

2023-01-02 18:54 UTC, SanyaBratashchuk approved these changes

2023-02-15 11:26 UTC, Anastasiia-Svintsova reviewed
- The user shouldn't be able to add an empty todo 

https://user-images.githubusercontent.com/99403198/219014130-1e493892-9b0a-478c-bc3b-0cb0d3d514c9.mov

- Look, when I try to remove a todo, I see the loader for several todos at one time. Fix it, please 

https://user-images.githubusercontent.com/99403198/219014508-1214eb38-afa8-4f11-aec3-a25ee59a157e.mov

2026-03-02 13:11 UTC, closed without merging