Done
mate-academy/react_todo-app-with-api pull request #254
Opened 2023-01-19 14:06 UTC by p-omogit-e

[DEMO LINK](https://p-omogit-e.github.io/react_todo-app-with-api/)

2023-01-20 07:32 UTC, tetiana-ivanchenko requested changes

2023-01-20 07:32 UTC, tetiana-ivanchenko commented on src/components/ErrorNotification/ErrorNotification.tsx
> +        || failedChangeError) && !closed && (
create function for it

2023-01-20 07:32 UTC, tetiana-ivanchenko commented on src/components/TodoList/TodoList.tsx
> +                  }}
```suggestion
                  onKeyUp={handleKeyUp}
```

2023-01-20 07:32 UTC, tetiana-ivanchenko commented on src/components/TodoList/TodoList.tsx
> +              }}
move it to the separate function

2023-01-20 07:32 UTC, tetiana-ivanchenko commented on src/components/TodoList/TodoList.tsx
> +                }}
move it to the separate function

2023-01-20 07:32 UTC, tetiana-ivanchenko commented on src/components/TodoList/TodoList.tsx
> +                }}
move it to the separate function

2023-01-20 07:32 UTC, tetiana-ivanchenko commented on src/App.tsx
> +  const [failedChangeError, setChangeError] = useState(false);
actually you can combine all errors be the using string with error text in the state, if the text is empty string - don't show error, if not - show

2023-01-24 13:35 UTC, p-omogit-e commented on src/App.tsx
> +  const [failedChangeError, setChangeError] = useState(false);
Проте в такому випадку, якщо буде декілька помилок зразу, то показуватиме тільки останню, все одно змінити?

2023-01-24 18:42 UTC, TarasHoliuk requested changes

2023-01-24 18:42 UTC, TarasHoliuk commented on src/App.tsx
> +  const [failedChangeError, setChangeError] = useState(false);
hmm, I guess you can at least combine it into one state with an object that contains different errors
1 state change -> 1 re-render

2023-01-24 18:42 UTC, TarasHoliuk commented on src/App.tsx
> +    return 3456;
I guess it could be 1 if the current Todos array is empty)

2023-01-24 18:42 UTC, TarasHoliuk commented on src/App.tsx
> +      case Filter.clearComplete:
I guess it shouldn't be in filter

2023-01-24 18:42 UTC, TarasHoliuk commented on src/App.tsx
> +  const [visibleTodoList, setVisibleList] = useState<Todo[]>([]);
no need to create a separate state for visible todos, you can count it based on `todoList`. It's better to save the filter value in state and get visibleTodos in this way: `const visibleTodos = filterTodos(todoList)` (less count of re-renders)

In places where you update visible todos (after update 1 todo, for example) change `todoList` instead - after `todoList` will be changed visibleTodos will be recalculated again.

2023-01-24 18:42 UTC, TarasHoliuk commented on src/App.tsx
> +  const deleteTodos = async (id: number) => {
why `Todos` - you delete 1 todo anyway. To avoid variable names duplication use word "remove" etc

2023-01-24 18:42 UTC, TarasHoliuk commented on src/App.tsx
> +  const onSubmitForm = async (event: React.FormEvent<HTMLFormElement>) => {
Now I don't able to add a new todo - always error
It should be fixed

2023-01-24 18:42 UTC, TarasHoliuk commented on src/App.tsx
> +              }}
```suggestion
              onClick={toggleAll}
```

2023-01-26 08:29 UTC, vlad-demchuk requested changes
it isn't working now(

2023-01-27 14:06 UTC, nazarmatsevych approved these changes
👍

2023-02-25 08:15 UTC, AlisaVlasova requested changes

2023-02-25 08:15 UTC, AlisaVlasova commented on src/components/ErrorNotification/ErrorNotification.tsx
> +          {errors.failedChange && 'Unable to update a todo \n'}
create Enum type for errors
```suggestion
          {ErrorType[error]}
```

2025-12-17 21:39 UTC, closed without merging