Solution
mate-academy/react_todo-app-with-api pull request #292
Opened 2023-01-30 21:50 UTC by superpooperxxx

[DEMO LINK](https://superpooperxxx.github.io/react_todo-app-with-api/

2023-02-03 09:02 UTC, solaryasha requested changes

2023-02-17 13:57 UTC, superpooperxxx commented on src/api/todos.ts
> +export const createTodo = (userId: number, todo: any) => {
fixed

2023-02-17 13:57 UTC, superpooperxxx commented on src/components/TodoAppHeader/TodoAppHeader.tsx
> +    }, []);
fixed

2023-02-17 14:21 UTC, superpooperxxx commented on src/App.tsx
> +      .then(() => {
fixed

2023-02-17 14:31 UTC, superpooperxxx commented on src/App.tsx
> +    ));
fixed

2023-02-17 14:32 UTC, superpooperxxx commented on src/App.tsx
> +            ? { ...todo, ...todoField }
fixed

2023-03-13 11:54 UTC, ivan-kadykalo approved these changes
Good job 🔥

2025-06-13 07:14 UTC, closed without merging