Develop
mate-academy/react_todo-app-with-api pull request #315
Opened 2023-02-02 06:41 UTC by panianchuk

https://panianchuk.github.io/react_todo-app-with-api/

2023-02-02 17:46 UTC, loralevitska requested changes
Keep up the good work! Some comments to fix:
Remove default outline 
![image](https://user-images.githubusercontent.com/70009205/216399696-50a0f9ce-6911-4c38-b876-7dc1bad5abea.png)
![image](https://user-images.githubusercontent.com/70009205/216399857-d6b6fceb-cdb8-4e17-8291-3a89f03dd3c6.png)

2023-02-02 17:46 UTC, loralevitska commented on src/api/todos.ts
> +  return client.patch<Todo>(`/todos/${id}`, { title: data });
It is better to separate the logic for such things, or use objects where you overwrite the necessary data

2023-02-02 17:46 UTC, loralevitska commented on src/components/Header.tsx
> +/* eslint-disable jsx-a11y/control-has-associated-label */
Try to fix this rule and remove comments. Fix all cases if present

2023-02-02 17:46 UTC, loralevitska commented on src/components/TodoList.tsx
> +    </section>
Use semantic tags for list `ul` `li`
And remove comment

2023-02-03 15:27 UTC, loralevitska requested changes
Hi, I see you haven't fixed previous comments, maybe you did not push your changes? If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-02-03 15:27 UTC, loralevitska commented on src/components/Header.tsx
> +/* eslint-disable jsx-a11y/control-has-associated-label */
still not fixed

2023-02-03 15:27 UTC, loralevitska commented on src/api/todos.ts
> +  return client.patch<Todo>(`/todos/${id}`, { title: data });
not fixed

2023-02-04 09:39 UTC, SanyaBratashchuk approved these changes

2023-12-29 10:39 UTC, closed without merging