Develop
mate-academy/react_todo-app-with-api pull request #423
Opened 2023-04-09 16:57 UTC by Zelinskyi-Serhii

[DEMO LINK](https://Zelinskyi-Serhii.github.io/react_todo-app-with-api/)

2023-04-13 13:22 UTC, illiarerun requested changes

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +  const [activeInput, setActiveInput] = useState(true);
do you need it? you can calculate it based on `tempTodo` value
```suggestion
```

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +    (event: React.FormEvent<HTMLFormElement>) => {
everything that works with form should be In corresponding Form component, you should just pass callback for adding a todo to it

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +        setAllTodos(newTodos);
functional setState

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +      });
put it inside try/catch cause you call `update` here

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +        setAllTodos(newTodos);
functional setState

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +        </header>
Header component

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +        {(!allTodos.length && isRequest && !errorMessage)
this would be enough
```suggestion
        {(!allTodos.length
```

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +        {!allTodos.length && !errorMessage && !isRequest
would be enough
```suggestion
        {!allTodos.length && !errorMessage 
```

2023-04-13 13:22 UTC, illiarerun commented on src/App.tsx
> +        {!allTodos.length || (
why don't just use `&&`?
```suggestion
        {allTodos.length && (
```

2023-04-13 13:22 UTC, illiarerun commented on src/components/TodoList/TodoList.tsx
> +        {tempTodos && (
it's only one todo
```suggestion
        {tempTodo && (
```

2023-04-18 14:16 UTC, OleksiiBlezniuk commented on src/App.tsx
> +  const [loadingIds, setLoadingIds] = useState<Set<number>>(new Set());
interesting approach

2023-04-18 14:18 UTC, OleksiiBlezniuk commented on src/App.tsx
> +      setTempTodo(null);
Strange that you do it here, 'cause you did it in `handleAdd` method

2023-04-18 14:19 UTC, OleksiiBlezniuk commented on src/App.tsx
> +  const addLoadingTodo = useCallback((id: number) => {
```suggestion
  const setTodoLoading = useCallback((id: number) => {
```

2023-04-18 14:22 UTC, OleksiiBlezniuk commented on src/App.tsx
> +        )));
Should we filter array on every iteration? I guess better to move it outside forEach, or reuse existing `handleRemoveTodo` method here

2023-04-18 14:22 UTC, OleksiiBlezniuk commented on src/App.tsx
> +        setLoadingIds(new Set());
Same here, as soon as first todo will be removed - state will be cleared which is not logical

2023-04-18 14:24 UTC, OleksiiBlezniuk commented on src/App.tsx
> +        setLoadingIds(new Set());
Or reuse existing method for consistency, in any case duplicating logic with not logical changes is bad idea

2023-04-18 14:25 UTC, OleksiiBlezniuk commented on src/App.tsx
> +  ), [allTodos, filterType]).length;
Looks strange, let's save result of filter to constant and then save it length to separate constant

2023-04-18 14:26 UTC, OleksiiBlezniuk commented on src/App.tsx
> +  const isCompletedTodo = allTodos.length - countActiveTodos > 0;
which todo is completed? use more clear names

2023-04-18 14:26 UTC, OleksiiBlezniuk commented on src/App.tsx
> +  const isCompletedTodo = allTodos.length - countActiveTodos > 0;
```suggestion
  const isAnyTodoIsCompleted = allTodos.length - countActiveTodos > 0;
```

2023-04-18 14:27 UTC, OleksiiBlezniuk commented on src/App.tsx
> +        const findTodo = allTodos.find(todo => todo.id === todoId);
do it in setState, and use more clear name for it

2023-04-18 14:28 UTC, OleksiiBlezniuk commented on src/App.tsx
> +          }
Can we simplify this check? Such nested ifs looks complicated

2023-04-18 14:35 UTC, OleksiiBlezniuk commented on src/components/TododInfo/TodoInfo.tsx
> +          </form>
Would be nice to move it to separate component, but it's not critical

2023-04-19 16:17 UTC, OleksiiBlezniuk approved these changes

2023-04-19 16:17 UTC, OleksiiBlezniuk commented on src/App.tsx
> +        const updatedTodos = await Promise.all(allTodosPromises);
```suggestion
        const updatedTodos = await Promise.all(
          allTodos.map(async (todo) => {
            if (hasActiveTodo && !todo.completed) {
              setTodoLoading(todo.id);
            }
  
            if (!hasActiveTodo && todo.completed) {
              setTodoLoading(todo.id);
            }
  
            return updateTodoCompleted(todo.id, hasActiveTodo);
          })
        );
```

2023-04-19 16:17 UTC, OleksiiBlezniuk commented on src/components/ErrorMessage/ErrorMessage.tsx
> +    return (
I don't think this `return` keyword is needed here

2023-04-19 16:17 UTC, OleksiiBlezniuk commented on src/components/Form/Form.tsx
> +      </form>
```suggestion
        />
      </form>
```

2023-04-19 16:17 UTC, OleksiiBlezniuk commented on src/components/Header/Header.tsx
> +}) => (
```suggestion
  todoTitle,
  setTodoTitle,
  activeInput,
}) => (
```

2023-07-12 20:31 UTC, closed without merging