Develop
mate-academy/react_todo-app-with-api pull request #613
Opened 2023-07-04 20:49 UTC by Shevtsooov

[DEMO LINK](https://Shevtsooov.github.io/react_todo-app-with-api/)

2023-07-07 08:51 UTC, silchyn requested changes
Why temporary todo appears on the bottom if you put the actual todo at the top?

2023-07-07 09:12 UTC, Shevtsooov commented
@silchyn Oops, forgot to fix it. Thanks.

2023-07-07 15:23 UTC, silchyn requested changes
<img width="835" alt="image" src="https://github.com/mate-academy/react_todo-app-with-api/assets/30828805/637e5aa2-257a-4e25-b457-8465f3bce638">

2023-07-10 10:55 UTC, Shevtsooov commented
@silchyn Hi, I am sorry, but I am not quite sure where the issue is.
Could you elaborate it on, please?

2023-07-10 14:17 UTC, Shevtsooov commented
@silchyn Hi, thank you, fixed the issue.

2023-07-13 10:49 UTC, dinaminahi requested changes
Good job 👍 
let's add few improvements

2023-07-13 10:49 UTC, dinaminahi commented on src/App.tsx
> +  const [updatingTodoIds, setUpdatingTodoIds] = useState<number[]>([]);
Can we use just one state for both deleting and updating?

2023-07-13 10:49 UTC, dinaminahi commented on src/components/Header/Header.tsx
> +        onChange={(e) => setNewTodoTitle(e.target.value)}
Create  a handler for that

2023-07-13 10:49 UTC, dinaminahi commented on src/App.tsx
> +  const [newTodoTitle, setNewTodoTitle] = useState('');
Let's move this to Header component

2023-07-24 14:35 UTC, naziamoff approved these changes
looks nice 🔥 
See some suggestions on how you can improve the code

2023-07-24 14:35 UTC, naziamoff commented on src/App.tsx
> +  = useState<ErrorMessage>(ErrorMessage.noError);
```suggestion
  const [
    errorMessage, 
    setErrorMessage
  ] = useState<ErrorMessage>(ErrorMessage.noError);
```

2023-07-24 14:35 UTC, naziamoff commented on src/App.tsx
> +  = useState<ErrorMessage>(ErrorMessage.noError);
nice thing that you created enum for error 🔥

2023-07-24 14:35 UTC, naziamoff commented on src/App.tsx
> +  const [delUpdTodoIds, setDelUpdTodoIds] = useState<number[]>([]);
whts ths? dnt ndrstnd

2023-07-24 14:35 UTC, naziamoff commented on src/App.tsx
> +  //       });
You don't want to see commented code. It is confusing af, as you never now what the code owner wanted to tell with it

2023-07-24 14:35 UTC, naziamoff commented on src/components/Error/Error.tsx
> +        'notification', 'is-danger', 'is-light', 'has-text-weight-normal', {
```suggestion
        'notification is-danger is-light has-text-weight-normal', {
```

2023-07-24 14:35 UTC, naziamoff commented on src/types/TodoStatus.ts
> +}
Todo names usually start from capital letter
```suggestion
export enum TodoStatus {
  All = 'all',
  Active = 'active',
  Completed = 'completed',
}
```

2023-07-24 14:35 UTC, naziamoff commented on src/types/ErrorMessage.ts
> +  titleError = 'Title can\'t be empty',
you should capitalize these

2024-05-05 10:45 UTC, closed without merging