Solution
mate-academy/react_todo-app-with-api pull request #680
Opened 2023-07-31 15:57 UTC by outofs

https://outofs.github.io/react_todo-app-with-api/

2023-07-31 18:08 UTC, IraShtynda approved these changes
Looks great! Approving✨

2023-08-02 10:24 UTC, anstsot requested changes
Let’s add a few fixes to improve your code.
- don't change the todo if there is error on editing
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/22824431/52347f0b-ba25-45d7-8b1e-129d89066e86)

2023-08-02 10:24 UTC, anstsot commented on src/App.tsx
> +  const deleteTodo = (todoId: number) => {
use `useCallback` hook

2023-08-02 10:24 UTC, anstsot commented on src/App.tsx
> +  const updateTodo = (updatedTodo: Todo) => {
use `useCallback` hook

2023-08-02 10:24 UTC, anstsot commented on src/components/AddTodoForm/AddTodoForm.tsx
> +      id: Date.now(),
don't add `id` in `POST` request

2023-08-03 11:14 UTC, anstsot approved these changes
Good work, approving:sparkles:

2025-12-01 12:28 UTC, closed without merging