add last part Todo API
mate-academy/react_todo-app-with-api pull request #745
Opened 2023-08-16 09:57 UTC by AndriiYelieva

[DEMO LINK](https://AndriiYelieva.github.io/react_todo-app-with-api/)

2023-08-16 10:43 UTC, VitaliyBondarenko1982 requested changes
Please check comments and demo link
![Screenshot from 2023-08-16 13-43-21](https://github.com/mate-academy/react_todo-app-with-api/assets/33029864/77cf471e-8b81-4f9a-b8f2-a33b01c1ad7d)

2023-08-16 10:43 UTC, VitaliyBondarenko1982 commented on src/App.tsx
> +    return visibleTodos;
```suggestion
    switch (filterValue) {
      case FilterValue.Active: 
        return  todos.filter( (todo) => !todo.completed );
      case FilterValue.Completed: 
        return todos.filter( (todo) => todo.completed);
      default:
        return todos;
    }
```
return from switch filtered todos or all todos in default case.

2023-08-16 10:43 UTC, VitaliyBondarenko1982 commented on src/App.tsx
> +  const getFilteringTodos = () => {
```suggestion
  const filteredTodos = useMemo(() => {
```
wrap function in useMemo. it wiil return filteredTodos instead call function in each places where you need actual todos.

2023-08-16 10:43 UTC, VitaliyBondarenko1982 commented on src/components/Footer.tsx
> +        items left
use template string here
```suggestion
        {`${activeTodos.length} items left`}
```
check other similar cases

2023-08-16 10:43 UTC, VitaliyBondarenko1982 commented on src/components/TodoFilter.tsx
> +        onClick={() => setFilterValue(FilterValue.All)}
make one function factory in component which will be accept filter value and return arrow function.
call it in each link with proper value.
```
const handleFilter = (filterValue: FilterValue) => () => serFilterValue(filterValue)
```
```suggestion
        onClick={handleFilter(FilterValue.All)}
```

2023-08-16 11:45 UTC, IvanFesenko requested changes
Your app works incorrect
https://github.com/mate-academy/react_todo-app-with-api/assets/61904995/e057b184-3bf6-433e-9d7e-b23ee91bd472

2023-08-17 06:23 UTC, etojeDenys requested changes
looks broken :(

https://github.com/mate-academy/react_todo-app-with-api/assets/70220667/854c6824-f21e-450e-8a55-2f86960cc5d8

2023-08-17 09:44 UTC, VitaliyBondarenko1982 requested changes
Needs some improvements

2023-08-17 09:44 UTC, VitaliyBondarenko1982 commented on src/Components/TodoFooter.tsx
> +        }}
```suggestion
        onClick={deleteCompletedTodos}
```

2023-08-17 09:44 UTC, VitaliyBondarenko1982 commented on src/Components/TodoHeader.tsx
> +            });
it is redundant to load todos after finish update.
we can avoid this request to server. 
you can just update todos state.

2023-08-17 09:44 UTC, VitaliyBondarenko1982 commented on src/Components/TodoHeader.tsx
> +          })
same. suggest do not make request to server and just update locally todos.
check other similar cases

2023-08-17 09:44 UTC, VitaliyBondarenko1982 commented on src/Components/TodoItem.tsx
> +          )}
make separate funcitons for all handlers and jsx and pass reference here

2023-08-17 09:44 UTC, VitaliyBondarenko1982 commented on src/Components/TodoItem.tsx
> +          )}
make separate funcitons for all handlers and jsx and pass reference here
for example here something like that
check other similar cases

```
const handleClieckedFormSubmit = (id: string) => (event: React.FormEvent<HTMLFormElement>) => {
    // do all logic for submit
}
```

```suggestion
          onSubmit={handleClickedFormSubmit(todo.id)}
```

2023-08-17 09:44 UTC, VitaliyBondarenko1982 commented on src/Components/TodoFooter.tsx
> +          onClick={() => setFilterType(Filter.ALL)}
please fix this comment
![Screenshot from 2023-08-17 12-41-13](https://github.com/mate-academy/react_todo-app-with-api/assets/33029864/47dc7641-3680-478b-9e82-d7d3389d51d4)

2024-09-12 10:58 UTC, closed without merging