Task is done
mate-academy/react_todo-app-with-api pull request #751
Opened 2023-08-23 08:41 UTC by Konsttantin

[DEMO LINK](https://Konsttantin.github.io/react_todo-app-with-api/)

2023-08-23 16:50 UTC, TarasHoliuk requested changes
GJ :+1: 
I added a few minor comments

2023-08-23 16:50 UTC, TarasHoliuk commented on src/App.tsx
> +              }}
```suggestion
              onFilter={setFilter}
              onClear={deleteAllHandler}
```
Your `setFilter` is already a function that accepts such an argument - wrapper is redundant
It's fair for all similar cases

2023-08-23 16:50 UTC, TarasHoliuk commented on src/components/Header/Header.tsx
> +    if (!title.length) {
trim it - I can add Todo with spaces only:
![image](https://github.com/mate-academy/react_todo-app-with-api/assets/86923089/eaaa1c33-b741-4759-bddf-e38266681606)

2023-08-23 16:50 UTC, TarasHoliuk commented on src/components/TodoItem/TodoItem.tsx
> +  useEffect(() => setShowModal(isLoading), [isLoading]);
redundant `useEffect`
`isLoading` is a prop, so once its value changes component will be re-rendered

2023-08-23 16:50 UTC, TarasHoliuk commented on src/components/TodoItem/TodoItem.tsx
> +            onKeyUp={(e) => {
move functions with a few rows body to a variable and reuse in JSX

2023-08-23 16:50 UTC, TarasHoliuk commented on src/components/Main/Main.tsx
> +              {...tempTodo}
it's not good practice to pass props in such a way. It's better to explicitly pass each prop you need

2023-08-24 14:13 UTC, sTorba24 approved these changes
Well done!

2025-01-19 15:37 UTC, closed without merging