some fail
mate-academy/react_todo-app-with-api pull request #857
Opened 2023-10-06 13:31 UTC by DenisGurskiy

https://DenisGurskiy.github.io/react_todo-app-with-api/

2023-10-06 14:27 UTC, anastasiiavorobiova requested changes
Great work! The input field focus doesn't work properly, try to fix it and feel free to ask for help in the chat

2023-10-06 14:27 UTC, anastasiiavorobiova commented on src/components/TodoItem/TodoItem.tsx
> +//       </div >
Consider removing redundant code here

2023-10-07 20:09 UTC, DenisGurskiy commented
In VSCode all test pased.

2023-10-08 08:21 UTC, etojeDenys approved these changes
awesome

2024-03-12 15:57 UTC, closed without merging