Develop
mate-academy/react_todo-app-with-api pull request #966
Opened 2023-12-01 21:54 UTC by no4kar

[DEMO LINK](https://no4kar.github.io/react_todo-app-with-api/)

2023-12-02 13:46 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your page
This button doesn't work
<img width="163" alt="image" src="https://github.com/mate-academy/react_todo-app-with-api/assets/64750958/2b18864f-d82c-4412-a722-fcfeaedf27ce">

2023-12-03 18:06 UTC, volodymyr-soltys97 requested changes
Great!
Let's improve your code

2023-12-03 18:06 UTC, volodymyr-soltys97 commented on src/App.tsx
> +  // #endregion
Remove comments everywhere
```suggestion
```

2023-12-03 18:06 UTC, volodymyr-soltys97 commented on src/App.tsx
> +              isAnyTodoComplete={todos.some(todo => todo.completed)}
Move this logic to the helper function and use it here

2023-12-04 09:14 UTC, anastasiia-tilikina requested changes
Well done! We're almost here)

just one more minor fix.

these actions should always be in the center, even if 'clear completed' button is not shown.

![image](https://github.com/mate-academy/react_todo-app-with-api/assets/108538921/d3cc85f3-f1c1-486c-b2e7-46770cd10291)

2023-12-04 10:31 UTC, xiimiik approved these changes
Nice work!

2024-07-05 15:40 UTC, closed without merging